package com.pairforge.api.execution;

public enum FailureReason {
    DISPATCH_FAILED, DISPATCH_UNCONFIRMED, COMPILATION_ERROR, RUNTIME_ERROR,
    MEMORY_LIMIT, OUTPUT_LIMIT, INFRASTRUCTURE_INTERRUPTION
}
