import { randomBytes } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { connectSocket } from './socket'

async function registerAndLogin(page: Page) {
  const email = `browser-${randomBytes(8).toString('hex')}@example.test`
  const password = randomBytes(20).toString('hex')
  await page.goto('/register')
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Account created. Log in to continue.')
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Log in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Your workspace' })).toBeVisible()
  return { email, password }
}

function redisFixture(args: string[]) {
  const name = process.env.PAIRFORGE_E2E_REDIS_CONTAINER
  if (!name || !/^pairforge-e2e-[0-9a-f]{12}-redis$/.test(name)) throw new Error('Missing isolated Redis fixture')
  return execFileSync('docker', [args[0], name, ...args.slice(1)], { encoding: 'utf8', timeout: 10_000, windowsHide: true }).trim()
}

test('Redis outage is visible and recovery after data loss explicitly resets the document', async ({ page }) => {
  let connection: ReturnType<typeof connectSocket> | undefined
  await page.routeWebSocket('ws://127.0.0.1:18080/ws', socket => { connection = connectSocket(socket) })
  await registerAndLogin(page)
  await page.getByLabel('Room name', { exact: true }).fill('Redis recovery')
  await page.getByRole('button', { name: 'Create room', exact: true }).click()
  const id = await page.getByLabel('Room ID', { exact: true }).inputValue()
  await page.getByRole('link', { name: 'Open room', exact: true }).click()
  const status = page.getByRole('region', { name: 'Connection status', exact: true })
  const source = page.getByRole('textbox', { name: 'Source code', exact: true })
  const lines = page.locator('.monaco-editor .view-lines')
  await expect(status).toContainText('Connected')
  await source.focus(); await page.keyboard.press('Control+a'); await page.keyboard.insertText('saved before outage')
  await expect(status).toContainText('synchronized in Redis')
  await connection!.disconnect()
  await expect(status).toContainText('Disconnected')
  await source.focus(); await page.keyboard.press('Control+a'); await page.keyboard.insertText('offline backup')
  redisFixture(['pause'])
  try {
    await page.getByRole('button', { name: 'Reconnect', exact: true }).click()
    await expect(status).toContainText('Collaboration unavailable', { timeout: 15_000 })
    await expect(lines).toContainText('offline backup')
    await expect(page.getByRole('button', { name: 'Reconnect', exact: true })).toBeEnabled()
  } finally { redisFixture(['unpause']) }
  await page.getByRole('button', { name: 'Reconnect', exact: true }).click()
  await expect(status).toContainText('synchronized in Redis')
  await expect(lines).toContainText('saved before outage')
  await expect(page.getByLabel('Local draft backup', { exact: true })).toHaveValue('offline backup')
  await connection!.disconnect()
  await expect(status).toContainText('Disconnected')
  expect(redisFixture(['exec', 'redis-cli', 'DEL', `room:{${id}}:document`])).toBe('1')
  await page.getByRole('button', { name: 'Reconnect', exact: true }).click()
  await expect(status).toContainText('document reset')
  await expect(lines).toContainText('public class Main')
  await expect(page.getByLabel('Local draft backup', { exact: true })).toHaveValue('offline backup')
})

test('a lost collaboration connection keeps a visible local draft without replay', async ({ page }) => {
  let connection: ReturnType<typeof connectSocket> | undefined
  let connections = 0
  await page.routeWebSocket('ws://127.0.0.1:18080/ws', socket => {
    connections++; connection = connectSocket(socket)
  })
  await registerAndLogin(page)
  await page.getByLabel('Room name', { exact: true }).fill('Disconnected editing')
  await page.getByRole('button', { name: 'Create room', exact: true }).click()
  await page.getByRole('link', { name: 'Open room', exact: true }).click()
  const status = page.getByRole('region', { name: 'Connection status', exact: true })
  await expect(status).toContainText('Connected')
  const source = page.getByRole('textbox', { name: 'Source code', exact: true })
  await expect(source).toBeVisible()
  await connection!.disconnect()
  await expect(status).toContainText('Disconnected')
  await source.focus(); await page.keyboard.press('Control+a'); await page.keyboard.insertText('local copy after disconnect')
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('local copy after disconnect')
  await expect(status).toContainText('not synchronized')
  await page.getByRole('button', { name: 'Refresh room', exact: true }).click()
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('local copy after disconnect')
  await expect(page.getByRole('button', { name: 'Run', exact: true })).toBeDisabled()
  expect(connections).toBe(1)
  await page.getByRole('button', { name: 'Reconnect', exact: true }).click()
  await expect(status).toContainText('synchronized in Redis')
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('public class Main')
  await expect(page.getByLabel('Local draft backup', { exact: true })).toHaveValue('local copy after disconnect')
  expect(connections).toBe(2)
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.getByRole('button', { name: 'Copy draft', exact: true }).click()
  await expect(status).toContainText('Draft copied.')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('local copy after disconnect')
  await page.evaluate(() => { navigator.clipboard.writeText = async () => { throw new Error('Clipboard denied') } })
  await page.getByRole('button', { name: 'Copy draft', exact: true }).click()
  await expect(status).toContainText('Copy unavailable')
  await page.setViewportSize({ width: 390, height: 844 })
  // Monaco's ResizeObserver completes asynchronously after the viewport changes.
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(await page.evaluate(() => [localStorage.length, sessionStorage.length])).toEqual([0, 0])
  await page.getByRole('button', { name: 'Discard backup', exact: true }).click()
  await expect(page.getByLabel('Local draft backup', { exact: true })).toHaveCount(0)
})

test('real browser registration, creation, invitation admission, navigation and memory-only sessions', async ({ page, browser }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.clock.install()
  const owner = await registerAndLogin(page)
  await page.getByLabel('Room name', { exact: true }).fill('Browser acceptance room')
  await page.getByLabel('Default language').selectOption('PYTHON')
  await page.getByRole('button', { name: 'Create room', exact: true }).click()
  const id = await page.getByLabel('Room ID', { exact: true }).inputValue()
  const invitation = await page.getByLabel('Invitation token', { exact: true }).inputValue()
  expect(invitation).toMatch(/^[A-Za-z0-9_-]{43}$/)
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.getByRole('button', { name: 'Copy invitation' }).click()
  await expect(page.getByRole('status')).toHaveText('Invitation copied.')
  // Compare as a boolean so failure reports cannot print the invitation.
  expect(await page.evaluate(async ({ id, invitation }) =>
    (await navigator.clipboard.readText()).replace(/\r\n/g, '\n') === `Room ID: ${id}\nInvitation token: ${invitation}`, { id, invitation })).toBe(true)
  await page.getByRole('link', { name: 'Open room', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Browser acceptance room' })).toBeVisible()
  await expect(page.getByLabel('Editor language')).toHaveValue('PYTHON')
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('print("Hello, PairForge!")')
  await expect.poll(() => page.locator('.monaco-editor .view-lines span').evaluateAll(elements =>
    new Set(elements.filter(element => element.textContent?.trim()).map(element => getComputedStyle(element).color)).size)).toBeGreaterThan(1)
  expect(await page.evaluate(() => [localStorage.length, sessionStorage.length, document.cookie])).toEqual([0, 0, ''])
  expect(page.url().includes(invitation)).toBe(false)

  const guestContext = await browser.newContext({ baseURL: 'http://127.0.0.1:15173' })
  try {
    const guest = await guestContext.newPage()
    const account = await registerAndLogin(guest)
    // Full navigation intentionally loses the in-memory login; /login preserves only the room path.
    await guest.goto(`/rooms/${id}`)
    await expect(guest.getByRole('heading', { name: 'Welcome back' })).toBeVisible()
    await guest.getByLabel('Email', { exact: true }).fill(account.email)
    await guest.getByLabel('Password', { exact: true }).fill(account.password)
    await guest.getByRole('button', { name: 'Log in', exact: true }).click()
    await expect(guest.getByRole('alert')).toContainText('Room is unavailable')
    await expect(guest.getByRole('region', { name: 'Code editor', exact: true })).toHaveCount(0)
    await guest.getByRole('link', { name: 'Back to dashboard' }).click()
    await guest.getByLabel('Room ID to join').fill(id)
    await guest.getByLabel('Invitation token to join').fill('x'.repeat(43))
    await guest.getByRole('button', { name: 'Join room', exact: true }).click()
    await expect(guest.getByRole('alert')).toContainText('Room is unavailable')
    await guest.getByLabel('Invitation token to join').fill(invitation)
    await guest.getByRole('button', { name: 'Join room', exact: true }).click()
    await expect(guest.getByRole('heading', { name: 'Browser acceptance room' })).toBeVisible()
    await guest.getByRole('link', { name: 'Back to dashboard' }).click()
    await expect(guest.getByRole('link', { name: 'Browser acceptance room' })).toBeVisible()
    await guest.getByRole('button', { name: 'Log out' }).click()
    await expect(guest.getByRole('heading', { name: 'Welcome back' })).toBeVisible()
    await expect(guest.getByText('Browser acceptance room')).toHaveCount(0)
  } finally { await guestContext.close() }

  await page.reload()
  await expect(page.getByRole('heading', { name: 'Welcome back' })).toBeVisible()
  await page.getByLabel('Email', { exact: true }).fill(owner.email)
  await page.getByLabel('Password', { exact: true }).fill(owner.password)
  await page.getByRole('button', { name: 'Log in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Browser acceptance room' })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Source code', exact: true })).toBeVisible()
  await page.clock.fastForward(901_000)
  await expect(page.getByText('Your session expired. Please log in again.')).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Source code', exact: true })).toHaveCount(0)
  expect(errors).toEqual([])
})

test('browser handles API loss and authenticated 401 without automatic writes', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await registerAndLogin(page)
  await expect(page.getByText('No rooms on this page. Create one or join with an invitation.')).toBeVisible()
  let attempts = 0
  await page.route('**/api/rooms', async route => { attempts++; await route.abort('failed') })
  await page.getByLabel('Room name', { exact: true }).fill('Uncertain room')
  await page.getByRole('button', { name: 'Create room', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Cannot reach the server')
  await expect(page.getByRole('status')).toContainText('Retrying may create another room')
  expect(attempts).toBe(1)
  await page.route('**/api/rooms?*', route => route.fulfill({ status: 401, contentType: 'application/json',
    body: JSON.stringify({ message: 'Authentication required' }), headers: { 'Access-Control-Allow-Origin': 'http://127.0.0.1:15173' } }))
  await page.getByRole('button', { name: 'Refresh rooms' }).click()
  await expect(page.getByText('Your session expired. Please log in again.')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('maximum-length room names remain readable on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await registerAndLogin(page)
  const name = 'R'.repeat(120)
  await page.getByLabel('Room name', { exact: true }).fill(name)
  await page.getByRole('button', { name: 'Create room', exact: true }).click()
  await page.getByRole('link', { name: 'Open room', exact: true }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('link', { name: 'Back to dashboard' }).click()
  await expect(page.getByRole('link', { name, exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('production Monaco shares a document, preserves local undo and loads a local worker', async ({ page }) => {
  const errors: string[] = []
  const workers: string[] = []
  const writes: string[] = []
  const sockets: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('worker', worker => workers.push(worker.url()))
  page.on('websocket', socket => sockets.push(socket.url()))
  const account = await registerAndLogin(page)
  await page.getByLabel('Room name', { exact: true }).fill('Monaco acceptance room')
  await page.getByRole('button', { name: 'Create room', exact: true }).click()
  await page.getByRole('link', { name: 'Open room', exact: true }).click()
  const source = page.getByRole('textbox', { name: 'Source code', exact: true })
  const lines = page.locator('.monaco-editor .view-lines')
  await expect(source).toBeVisible()
  await expect(page.getByRole('region', { name: 'Connection status', exact: true })).toContainText('Connected')
  await expect(lines).toContainText('public class Main')
  page.on('request', request => {
    if (request.url().includes('/api/') && request.method() !== 'GET' && request.method() !== 'OPTIONS') writes.push(request.method())
  })
  await source.focus()
  await page.keyboard.press('Control+a')
  await page.keyboard.insertText('pairforgeDraft = 42')
  await expect(lines).toContainText('pairforgeDraft = 42')
  await page.keyboard.press('Control+z')
  await expect(lines).not.toContainText('42')
  await page.keyboard.press('Control+Shift+z')
  await expect(lines).toContainText('pairforgeDraft = 42')
  await page.getByLabel('Editor language').selectOption('PYTHON')
  await expect(page.getByRole('heading', { name: 'main.py', exact: true })).toBeVisible()
  await expect(lines).toContainText('pairforgeDraft = 42')
  await source.focus()
  await page.keyboard.press('Control+z')
  await expect(lines).not.toContainText('42')
  await page.keyboard.press('Control+Shift+z')
  await expect(lines).toContainText('pairforgeDraft = 42')
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await page.keyboard.insertText('pair')
  await page.keyboard.press('Control+Space')
  await expect.poll(() => workers.some(url => /\/assets\/editor\.worker-.*\.js$/.test(url))).toBe(true)
  // A suggestion from the previous line proves the production worker responded.
  await expect(page.getByRole('listbox', { name: 'Suggest' }).getByText('pairforgeDraft', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Refresh room', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Refresh room', exact: true })).toBeEnabled()
  await expect(lines).toContainText('pairforgeDraft = 42')
  await expect(page.getByLabel('Editor language')).toHaveValue('PYTHON')
  await page.route('**/api/rooms/*', route => route.fulfill({ status: 503, contentType: 'application/json',
    body: JSON.stringify({ message: 'Service unavailable' }) }))
  await page.getByRole('button', { name: 'Refresh room', exact: true }).click()
  await expect(page.locator('.error[role="alert"]')).toContainText('Service unavailable')
  await expect(lines).toContainText('pairforgeDraft = 42')
  await page.unroute('**/api/rooms/*')
  await expect(page.getByRole('button', { name: 'Run', exact: true })).toBeEnabled()
  await expect(page.getByRole('region', { name: 'Output', exact: true })).toContainText('Run submits the visible source')
  await expect(page.getByRole('region', { name: 'stdout', exact: true })).toContainText('No output yet.')
  await expect(page.getByRole('region', { name: 'stderr', exact: true })).toContainText('No errors yet.')
  await expect(page.getByRole('region', { name: 'Connection status', exact: true })).toContainText('Connected')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(source).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(await page.evaluate(() => [localStorage.length, sessionStorage.length])).toEqual([0, 0])
  expect(writes).toEqual([])
  expect(sockets).toEqual(['ws://127.0.0.1:18080/ws'])
  expect(workers.every(url => new URL(url).origin === 'http://127.0.0.1:15173')).toBe(true)

  await page.getByRole('link', { name: 'Back to dashboard' }).click()
  await expect(source).toHaveCount(0)
  await page.getByRole('link', { name: 'Monaco acceptance room', exact: true }).click()
  await expect(lines).toContainText('pairforgeDraft = 42')
  await expect(page.getByLabel('Editor language')).toHaveValue('PYTHON')
  await source.focus()
  await page.keyboard.press('Control+a')
  await page.keyboard.insertText('shared across reload')
  await expect(page.getByRole('region', { name: 'Connection status', exact: true })).toContainText('synchronized in Redis')
  await page.reload()
  await page.getByLabel('Email', { exact: true }).fill(account.email)
  await page.getByLabel('Password', { exact: true }).fill(account.password)
  await page.getByRole('button', { name: 'Log in', exact: true }).click()
  await expect(lines).toContainText('shared across reload')
  await page.getByRole('button', { name: 'Log out', exact: true }).click()
  await expect(source).toHaveCount(0)
  expect(errors).toEqual([])
})

test('failed production editor assets show a recoverable error without breaking room navigation', async ({ page }) => {
  const account = await registerAndLogin(page)
  await page.getByLabel('Room name', { exact: true }).fill('Editor failure room')
  await page.getByRole('button', { name: 'Create room', exact: true }).click()
  await page.route('**/assets/monaco-*.js', route => route.abort('failed'))
  await page.getByRole('link', { name: 'Open room', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('The editor could not load')
  await expect(page.getByRole('button', { name: 'Run', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Retry editor', exact: true })).toBeVisible()
  await page.unroute('**/assets/monaco-*.js')
  await page.getByRole('button', { name: 'Retry editor', exact: true }).click()
  // Browsers may cache a failed module import until reload.
  await page.reload()
  await page.getByLabel('Email', { exact: true }).fill(account.email)
  await page.getByLabel('Password', { exact: true }).fill(account.password)
  await page.getByRole('button', { name: 'Log in', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Source code', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Back to dashboard' }).click()
  await expect(page.getByRole('heading', { name: 'Your workspace' })).toBeVisible()
})

test('language switching still highlights when later script downloads are unavailable', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await registerAndLogin(page)
  await page.getByLabel('Room name', { exact: true }).fill('Offline language assets')
  await page.getByRole('button', { name: 'Create room', exact: true }).click()
  await page.getByRole('link', { name: 'Open room', exact: true }).click()
  const source = page.getByRole('textbox', { name: 'Source code', exact: true })
  await expect(source).toBeVisible()
  await expect(page.getByLabel('Editor language')).toBeEnabled()
  await page.route('**/*.js', route => route.abort('failed'))
  await page.getByLabel('Editor language').selectOption('PYTHON')
  await source.focus()
  await page.keyboard.press('Control+a')
  await page.keyboard.insertText('print("offline draft")')
  await expect.poll(() => page.locator('.monaco-editor .view-lines span').evaluateAll(elements =>
    new Set(elements.filter(element => element.textContent?.trim()).map(element => getComputedStyle(element).color)).size)).toBeGreaterThan(1)
  expect(errors).toEqual([])
})

test('two authorized accounts exchange edits and language changes without execution', async ({ page, browser }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await registerAndLogin(page)
  await page.getByLabel('Room name', { exact: true }).fill('Shared acceptance room')
  await page.getByRole('button', { name: 'Create room', exact: true }).click()
  const id = await page.getByLabel('Room ID', { exact: true }).inputValue()
  const invitation = await page.getByLabel('Invitation token', { exact: true }).inputValue()
  await page.getByRole('link', { name: 'Open room', exact: true }).click()
  const context = await browser.newContext({ baseURL: 'http://127.0.0.1:15173' })
  try {
    const guest = await context.newPage()
    let guestSocket: ReturnType<typeof connectSocket> | undefined
    await guest.routeWebSocket('ws://127.0.0.1:18080/ws', socket => { guestSocket = connectSocket(socket) })
    guest.on('pageerror', error => errors.push(error.message))
    await registerAndLogin(guest)
    await guest.getByLabel('Room ID to join').fill(id)
    await guest.getByLabel('Invitation token to join').fill(invitation)
    await guest.getByRole('button', { name: 'Join room', exact: true }).click()
    for (const editor of [page, guest]) {
      await expect(editor.getByRole('region', { name: 'Connection status', exact: true })).toContainText('Connected')
      await expect(editor.getByRole('textbox', { name: 'Source code', exact: true })).toBeVisible()
    }
    const ownerSource = page.getByRole('textbox', { name: 'Source code', exact: true })
    await ownerSource.focus(); await page.keyboard.press('Control+a'); await page.keyboard.insertText('print("from owner")')
    await page.getByLabel('Editor language').selectOption('PYTHON')
    await expect(guest.locator('.monaco-editor .view-lines')).toContainText('print("from owner")')
    await expect(guest.getByLabel('Editor language')).toHaveValue('PYTHON')
    const guestSource = guest.getByRole('textbox', { name: 'Source code', exact: true })
    await guestSource.focus(); await guest.keyboard.press('Control+a'); await guest.keyboard.insertText('print("from guest")')
    await expect(page.locator('.monaco-editor .view-lines')).toContainText('print("from guest")')
    await expect(page.getByRole('button', { name: 'Run', exact: true })).toBeEnabled()
    const guestStatus = guest.getByRole('region', { name: 'Connection status', exact: true })
    await guestSocket!.disconnect()
    await expect(guestStatus).toContainText('Disconnected')
    await guestSource.focus(); await guest.keyboard.press('Control+a'); await guest.keyboard.insertText('private offline draft')
    await ownerSource.focus(); await page.keyboard.press('Control+a'); await page.keyboard.insertText('latest while guest away')
    await page.getByLabel('Editor language').selectOption('JAVA')
    await expect(page.getByRole('region', { name: 'Connection status', exact: true })).toContainText('synchronized in Redis')
    await guest.getByRole('button', { name: 'Reconnect', exact: true }).click()
    await expect(guestStatus).toContainText('synchronized in Redis')
    await expect(guest.locator('.monaco-editor .view-lines')).toContainText('latest while guest away')
    await expect(guest.getByLabel('Editor language')).toHaveValue('JAVA')
    await expect(guest.getByLabel('Local draft backup', { exact: true })).toHaveValue('private offline draft')
    await expect(page.locator('.monaco-editor .view-lines')).toContainText('latest while guest away')
    await guestSource.focus(); await guest.keyboard.press('Control+a'); await guest.keyboard.insertText('deliberate edit after recovery')
    await expect(page.locator('.monaco-editor .view-lines')).toContainText('deliberate edit after recovery')
    await guest.getByRole('button', { name: 'Log out', exact: true }).click()
    await expect(guestSource).toHaveCount(0)
    await expect(guest.getByLabel('Local draft backup', { exact: true })).toHaveCount(0)
    expect(errors).toEqual([])
  } finally { await context.close() }
})
